version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/core/etc/nginx.conf:/etc/nginx/nginx.conf
      - /home/core/etc/conf.d/nginx.brozish.conf:/etc/nginx/conf.d/default.conf
      - /home/core/etc/conf.d/nginx.gitlab.conf:/etc/nginx/conf.d/nginx.gitlab.conf
      - /home/core/etc/conf.d/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - /home/core/etc/letsencrypt:/etc/letsencrypt

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.brozish.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.brozish.com'
        nginx['redirect_http_to_https'] = true
        nginx['redirect_http_to_https_port'] = 8002
        nginx['http2_enabled'] = true
        nginx['listen_port'] = 4443
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        letsencrypt['enable'] = false

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.mailgun.org"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_user_name'] = "postmaster@your_domain"
        gitlab_rails['smtp_password'] = "your_password"
        gitlab_rails['smtp_domain'] = "your_domain"
        gitlab_rails['gitlab_email_from'] = "brozish@your_domain"
        gitlab_rails['gitlab_email_reply_to'] = "brozish@your_domain"
    ports:
      - '8002:80'
      - '4443:443'
      - '2224:22'
    volumes:
      - /home/core/etc/gitlab:/etc/gitlab
      - /home/core/etc/gitlab/logs:/var/log/gitlab
      - /home/core/etc/gitlab/data:/var/opt/gitlab
