version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /home/core/etc/nginx.conf:/etc/nginx/nginx.conf
      - /home/core/etc/nginx.brozish.conf:/etc/nginx/conf.d/default.conf
      - /home/core/etc/nginx.www.brozish.conf:/etc/nginx/conf.d/brozish.conf
      - /home/core/etc/letsencrypt:/etc/letsencrypt
